//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePoint_Link.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.myitopia.com/_vti_bin/Copy.asmx")]
        public string ITopiaSharePointOutlookAddin_SPCopyService_Copy {
            get {
                return ((string)(this["ITopiaSharePointOutlookAddin_SPCopyService_Copy"]));
            }
            set {
                this["ITopiaSharePointOutlookAddin_SPCopyService_Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.myitopia.com/_vti_bin/Lists.asmx")]
        public string ITopiaSharePointOutlookAddin_ListWebService_Lists {
            get {
                return ((string)(this["ITopiaSharePointOutlookAddin_ListWebService_Lists"]));
            }
            set {
                this["ITopiaSharePointOutlookAddin_ListWebService_Lists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.myitopia.com/_vti_bin/Authentication.asmx")]
        public string ITopiaSharePointOutlookAddin_AuthenticationService_Authentication {
            get {
                return ((string)(this["ITopiaSharePointOutlookAddin_AuthenticationService_Authentication"]));
            }
            set {
                this["ITopiaSharePointOutlookAddin_AuthenticationService_Authentication"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.myitopia.com/_vti_bin/Authentication.asmx")]
        public string SharePoint_Link_AuthenticationService_Authentication {
            get {
                return ((string)(this["SharePoint_Link_AuthenticationService_Authentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.myitopia.com/_vti_bin/Lists.asmx")]
        public string SharePoint_Link_ListWebService_Lists {
            get {
                return ((string)(this["SharePoint_Link_ListWebService_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.myitopia.com/_vti_bin/Copy.asmx")]
        public string SharePoint_Link_SPCopyService_Copy {
            get {
                return ((string)(this["SharePoint_Link_SPCopyService_Copy"]));
            }
        }
    }
}
